version: "3"

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9000:9000"
      - "10070:50070"

  datanode:
    image: dlpgft/datanode:hadoop2.7.4-0.2
    container_name: datanode
    hostname: datanode.gft.com
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    ports:
      - "10075:50075"

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env
    ports:
      - "8088:8088"

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - "8042:8042"

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"

  hive-server:
    image: dlpgft/hive_server_sqoop:hadoop2.7.4-0.1
    container_name: hiveserver
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
      SQOOP_HOME: /opt/sqoop
      HIVE_CONF_DIR: /opt/hive/conf
    domainname: hadoop
    ports:
      - "10000:10000"
    volumes:
      - ./hive/shared:/tmp/shared

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hivemetastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    domainname: hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    depends_on:
      - namenode
      - hive-metastore-postgresql
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: dlpgft/postgresql_metastore:0.30
    container_name: hivemetastorepostgresql
    ports:
      - "5432:5432"

  hue:
    image: dlpgft/hue:0.3
    container_name: hue
    ports:
      - 8000:8888
    depends_on:
      - namenode
      - hive-metastore-postgresql
    env_file:
      - ./hadoop.env

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka: 
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  zeppelin:
    container_name: zeppelin
    image: apache/zeppelin:0.8.1
    ports:
      - 9999:8080
    volumes:
      - ./zeppelin/shared:/tmp/shared
      - ./zeppelin/data:/zeppelin/data
      - ./zeppelin/notebook:/zeppelin/notebook

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver: